[build]
  command = "npm run build:prod"
  publish = "dist/portfolio/browser"

[functions]
  directory = "dist/portfolio/server"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200